### ISSUE TITLE
HCI Core: Invalid client version - still not working for me

### ISSUE THREAD

**Issue by matze548** [deg0nz/MMM-PublicTransportBerlin#242]
Since more than a couple of weeks the module isn't working anymore

This is from the Logs:

```
### SYSTEM:   manufacturer: ; model: Docker Container; virtual: false
### OS:       platform: linux; distro: Debian GNU/Linux; release: 12; arch: arm; kernel: 6.1.21-v7+
### VERSIONS: electron: 31.6.0; used node: 20.17.0; installed node: 22.11.0; npm: 10.9.0; pm2: 
### OTHER:    timeZone: Europe/Berlin; ELECTRON_ENABLE_GPU: undefined 
```

also this:

```
[2024-11-17 15:53:28.985] [ERROR] Error initializing fetcher: Error: CLIENTVERSION: HCI Core: Invalid client version 
[2024-11-17 15:53:29.087] [ERROR] HafasError: CLIENTVERSION: HCI Core: Invalid client version
    at checkIfResponseIsOk (file:///opt/magic_mirror/modules/MMM-PublicTransportBerlin/node_modules/hafas-client/lib/request.js:91:9)
    at Object.request (file:///opt/magic_mirror/modules/MMM-PublicTransportBerlin/node_modules/hafas-client/lib/request.js:191:2)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.stop (file:///opt/magic_mirror/modules/MMM-PublicTransportBerlin/node_modules/hafas-client/index.js:447:25)
    at async BvgFetcher.getStationName (/opt/magic_mirror/modules/MMM-PublicTransportBerlin/BvgFetcher.js:28:21)
    at async Class.createFetcher (/opt/magic_mirror/modules/MMM-PublicTransportBerlin/node_helper.js:22:29) {
  isHafasError: true,
  code: null,
  isCausedByServer: false,
  hafasCode: 'CLIENTVERSION',
  request: Request {
    size: 0,
    timeout: 0,
    follow: 20,
    compress: true,
    counter: 0,
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 2,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    [Symbol(Body internals)]: {
      body: <Buffer 7b 22 6c 61 6e 67 22 3a 22 64 65 22 2c 22 73 76 63 52 65 71 4c 22 3a 5b 7b 22 6d 65 74 68 22 3a 22 4c 6f 63 44 65 74 61 69 6c 73 22 2c 22 72 65 71 22 ... 193 more bytes>,
      disturbed: false,
      error: null
    },
    [Symbol(Request internals)]: {
      method: 'POST',
      redirect: 'follow',
      headers: [Headers],
      parsedURL: [Url],
      signal: null
    }
  },
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://bvg-apps-ext.hafas.de/bin/mgate.exe?',
      status: 200,
      statusText: 'OK',
      headers: [Headers],
      counter: 0
    }
  },
  url: 'https://bvg-apps-ext.hafas.de/bin/mgate.exe?',
  hafasResponseId: 'di48vhac6wg8wm4k',
  hafasMessage: 'HCI Core: Invalid client version'
} 
[2024-11-17 15:53:29.901] [LOG]   Error while fetching departures (for module instance module_11_MMM-PublicTransportBerlin): Error: CLIENTVERSION: HCI Core: Invalid client version 
[2024-11-17 15:55:22.587] [LOG]   Error while fetching departures (for module instance module_11_MMM-PublicTransportBerlin): Error: CLIENTVERSION: HCI Core: Invalid client version 
```

I used the docker version to install the Magic Mirror it is at version 2.29.0 the MMM-PublicTransportBerlin Version is 2.1.1

**Comment by KristjanESPERANTO** [comment]
Did you run `npm ci` after you updated the module?

**Comment by KristjanESPERANTO** [comment]
No problem, it happens to the best :smile:
