### ISSUE TITLE
Startup crash with example config

### ISSUE THREAD

**Issue by malte1989** [deg0nz/MMM-PublicTransportBerlin#46]
Widget crashes, even with the default configuration.
node_modules were installed.

Transportation fetcher created. (Station ID: 9160003)
Whoops! There was an uncaught exception...
TypeError: dbClient.departures is not a function
    at DbFetcher.fetchDepartures (/home/pi/MagicMirror/modules/MMM-PublicTransportDB/DbFetcher.js:56:21)
    at Class.getDepartures (/home/pi/MagicMirror/modules/MMM-PublicTransportDB/node_helper.js:39:44)
    at Class.createFetcher (/home/pi/MagicMirror/modules/MMM-PublicTransportDB/node_helper.js:28:14)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-PublicTransportDB/node_helper.js:117:18)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at Socket.emit (events.js:182:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by deg0nz** [comment]
I think you are in the wrong repository. The error message you sent ist from another module called `MMM-PublicTransportDB`. This is `MMM-PublicTransportBerlin`.

Maybe you have it from here: https://github.com/ostfilinchen/MMM-PublicTransportDB
Or the fork of my module for DB transportation here (which is more likely): https://github.com/olexs/MMM-PublicTransportDB

The code bases of these projects differ a lot, since the fork happened some time ago. Do please open an issue in the respective repository.

**Comment by malte1989** [comment]
You are right

**Comment by deg0nz** [comment]
I just wanted to make that suggestion :D
Here's a link to [MMM-PublicTransportHafas](https://github.com/raywo/MMM-PublicTransportHafas)
