### ISSUE TITLE
 Error: station ID must be a valid IBNR.

### ISSUE THREAD

**Issue by hildwin** [deg0nz/MMM-PublicTransportBerlin#62]
I found in the logs an error regarding a missing INBR:

`[01.10.2021 15:58.44.520] [ERROR] Error: station ID must be a valid IBNR.
    at Object.formatStation (/home/pi/MagicMirror/modules/MMM-PublicTransportBerlin/node_modules/hafas-client/p/bvg/$
    at Object.stop (/home/pi/MagicMirror/modules/MMM-PublicTransportBerlin/node_modules/hafas-client/index.js:285:53)
    at BvgFetcher.getDirectionDescriptor (/home/pi/MagicMirror/modules/MMM-PublicTransportBerlin/BvgFetcher.js:35:39)
    at Class.sendInit (/home/pi/MagicMirror/modules/MMM-PublicTransportBerlin/node_helper.js:47:47)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
`
I've got the right stationId by the BVG-API.

**Comment by KristjanESPERANTO** [comment]
The module works for me. Please show your config of the module.

**Comment by deg0nz** [comment]
I'm closing this isue because there was no response from the issuer. Feel free to reopen if needed.
